-- Seeding authorized_users from CSV
INSERT INTO public.authorized_users (email, full_name, role, status) VALUES
('adamaria@madrepaulina.cl', 'Ada Maria Zapata Herrera', 'teacher', 'active'),
('achylik@madrepaulina.cl', 'Alexander Arturo Chylik Ríos', 'teacher', 'suspended'),
('acontreras@madrepaulina.cl', 'Ana Edith Contreras', 'teacher', 'active'),
('acisternas@madrepaulina.cl', 'Ana Edith Cisternas Parra', 'teacher', 'active'),
('ajara@madrepaulina.cl', 'Ana Gisela Jara Muñoz', 'teacher', 'suspended'),
('avillarroel@madrepaulina.cl', 'Ana Luisa Villarroel', 'teacher', 'active'),
('avalderrama@madrepaulina.cl', 'Ana María Valderrama', 'teacher', 'active'),
('atorres@madrepaulina.cl', 'Andrea Torres Bousoño', 'teacher', 'active'),
('ayarur@madrepaulina.cl', 'Andrés Alberto Yarur Luengo', 'teacher', 'suspended'),
('apena@madrepaulina.cl', 'Anely Peña Lagazzi', 'teacher', 'active'),
('apichun@madrepaulina.cl', 'Angela Pichún Quintupil', 'teacher', 'active'),
('amunoz@madrepaulina.cl', 'Angela Victoria Muñoz Figueroa', 'teacher', 'active'),
('agonzalez@madrepaulina.cl', 'Angelica Gonzalez Flores', 'teacher', 'suspended'),
('avejar@madrepaulina.cl', 'Angeline Vejar Gallardo', 'teacher', 'active'),
('aconoman@madrepaulina.cl', 'Angeline Coñoman Hernández', 'teacher', 'active'),
('agaldames@madrepaulina.cl', 'Astrid Marisol Galdames Sandoval', 'teacher', 'active'),
('beurra@madrepaulina.cl', 'Bernardita Urra Lipin', 'teacher', 'suspended'),
('bvalle@madrepaulina.cl', 'Bismarck Valle', 'teacher', 'active'),
('bramirez@madrepaulina.cl', 'Bruno Ramírez Mella', 'teacher', 'active'),
('cgonzalez@madrepaulina.cl', 'Camila González', 'teacher', 'suspended'),
('ccona@madrepaulina.cl', 'Camila Cona Mariñan', 'teacher', 'active'),
('cescobar@madrepaulina.cl', 'Camila Constanza Escobar Escobar', 'teacher', 'suspended'),
('carismendi@madrepaulina.cl', 'Camila Paz Arismendi Ubilla', 'teacher', 'suspended'),
('ccampos@madrepaulina.cl', 'Camila Paz Campos Díaz', 'teacher', 'suspended'),
('cramirez@madrepaulina.cl', 'Camila Valentina Ramirez Carreño', 'teacher', 'suspended'),
('cerices@madrepaulina.cl', 'Carlos Andres Erices Godoy', 'teacher', 'active'),
('cmaldonado@madrepaulina.cl', 'Carmen Gloria Maldonado Sáez', 'teacher', 'suspended'),
('cnavarrete@madrepaulina.cl', 'Carol Navarrete Parada', 'teacher', 'suspended'),
('cmontero@madrepaulina.cl', 'Carola Montero', 'teacher', 'suspended'),
('csepulveda@madrepaulina.cl', 'Carolina Andrea Sepúlveda Miranda', 'teacher', 'suspended'),
('csaez@madrepaulina.cl', 'Carolina Elena Sáez Carrasco', 'teacher', 'active'),
('chargous@madrepaulina.cl', 'Catalina Hargous González', 'teacher', 'active'),
('cllarena@madrepaulina.cl', 'Cecilia Patricia Llarena Lagos', 'teacher', 'active'),
('ctoledo@madrepaulina.cl', 'Celena Toledo', 'teacher', 'active'),
('cdelafuente@madrepaulina.cl', 'Cindy Andrea De la Fuente Aceitón', 'teacher', 'active'),
('cvera@madrepaulina.cl', 'Cinthya Vera', 'teacher', 'suspended'),
('csantelices@madrepaulina.cl', 'Claudia Andrea Isabel Santelices López', 'teacher', 'active'),
('cgrandon@madrepaulina.cl', 'Claudia Paola Grandón Gutierrez', 'teacher', 'active'),
('contacto@madrepaulina.cl', 'Colegio Madre Paulina', 'teacher', 'active'),
('comisionaniversario@madrepaulina.cl', 'Comisión Aniversario', 'teacher', 'active'),
('comisionaniversario1@madrepaulina.cl', 'Comisión Aniversario1', 'teacher', 'active'),
('ccofre@madrepaulina.cl', 'CONSTANZA ANTONIA COFRE  CANALES', 'teacher', 'active'),
('cprueba@madrepaulina.cl', 'correo prueba', 'teacher', 'active'),
('creyes@madrepaulina.cl', 'Cristian Reyes Astudillo', 'teacher', 'active'),
('cmendez@madrepaulina.cl', 'Cristian Mendez', 'teacher', 'active'),
('chormazabal@madrepaulina.cl', 'Cristian Pablo Hormazabal Molina', 'teacher', 'active'),
('csagredo@madrepaulina.cl', 'Cristina Sagredo San Martín', 'teacher', 'active'),
('dchamblas@madrepaulina.cl', 'Daniela Chamblas Araneda', 'teacher', 'active'),
('dsalazar@madrepaulina.cl', 'Daniela Salazar Ramos', 'teacher', 'active'),
('dmarchant@madrepaulina.cl', 'Daniela Marchant Escribano', 'teacher', 'active'),
('dalarcon@madrepaulina.cl', 'Daniela Alarcón Vergara', 'teacher', 'active'),
('dbastias@madrepaulina.cl', 'Daniela Francesca Bastias Pereira', 'teacher', 'active'),
('dalcaino@madrepaulina.cl', 'Daniela Isamar Alcaino Mendoza', 'teacher', 'suspended'),
('dschaaf@madrepaulina.cl', 'Danyella Rocío Schaaf Castagnoli', 'teacher', 'suspended'),
('dquezada@madrepaulina.cl', 'Darling Vaitiare Quezada Pavez', 'teacher', 'active'),
('dchavez@madrepaulina.cl', 'Diego Chávez', 'teacher', 'suspended'),
('directoriomp@madrepaulina.cl', 'Directorio Madre Paulina', 'director', 'active'),
('eastete@madrepaulina.cl', 'Edgardo Andrés Astete Martínez', 'teacher', 'suspended'),
('eretamales@madrepaulina.cl', 'Eduardo Esteban Retamales Sepúlveda', 'teacher', 'active'),
('esilva@madrepaulina.cl', 'Elizabeth Carmen Silva Escamilla', 'teacher', 'active'),
('earaneda@madrepaulina.cl', 'Eric Andres Araneda Martinez', 'teacher', 'active'),
('ecarvajal@madrepaulina.cl', 'Esteban Carvajal Soto', 'teacher', 'suspended'),
('ealvial@madrepaulina.cl', 'Estefania Alvial Leiva', 'teacher', 'active'),
('emelo@madrepaulina.cl', 'Eyleen Melo Romo', 'teacher', 'active'),
('ffigueroa@madrepaulina.cl', 'Felipe Alberto Figueroa  Cancino', 'teacher', 'suspended'),
('fdelgado@madrepaulina.cl', 'Francisca Fernanda Delgado Jarpa', 'teacher', 'active'),
('gmorales@madrepaulina.cl', 'Geovanna Andrea Morales Salazar', 'teacher', 'active'),
('gquiroga@madrepaulina.cl', 'Germaine Quiroga Purralef', 'teacher', 'active'),
('goyanedel@madrepaulina.cl', 'Gisela Oyanedel Hernandez', 'teacher', 'active'),
('gfaundez@madrepaulina.cl', 'Gisela del Carmen Faundez Villablanca', 'teacher', 'active'),
('gvaldes@madrepaulina.cl', 'Gisela Olivia Valdés Betanzo', 'teacher', 'suspended'),
('galvial@madrepaulina.cl', 'Gladys del Carmen Alvial Fernández', 'teacher', 'active'),
('gparra@madrepaulina.cl', 'Gloria Andrea Parra Vargas', 'teacher', 'active'),
('hbustos@madrepaulina.cl', 'Hector Fabian Bustos Jara', 'teacher', 'suspended'),
('imella@madrepaulina.cl', 'Irene de las Nieves Mella Fuentes', 'teacher', 'active'),
('jirribarren@madrepaulina.cl', 'Jackeline Andrea Irribarren Varas', 'teacher', 'active'),
('jmartinez@madrepaulina.cl', 'Jacqueline Martinez', 'teacher', 'suspended'),
('jpuschel@madrepaulina.cl', 'Janella Puschel Kunz', 'teacher', 'active'),
('jtrujillo@madrepaulina.cl', 'Jasnna Trujillo Acosta', 'teacher', 'active'),
('jmendez@madrepaulina.cl', 'Javiera Méndez Muñoz', 'teacher', 'active'),
('jsegura@madrepaulina.cl', 'Jeremias Segura', 'teacher', 'active'),
('jvalenzuela@madrepaulina.cl', 'Jesenia Alejandra Valenzuela Pedreros', 'teacher', 'active'),
('jbastias@madrepaulina.cl', 'Jessica Bastias Vidal', 'teacher', 'active'),
('jmolina@madrepaulina.cl', 'Jessica Molina Isla', 'teacher', 'active'),
('jtroncoso@madrepaulina.cl', 'Jessica Ivonne Troncoso Sandoval', 'teacher', 'suspended'),
('jcancino@madrepaulina.cl', 'John Cancino', 'teacher', 'suspended'),
('jarroyo@madrepaulina.cl', 'Jonathan Alfonso Arroyo Barra', 'teacher', 'active'),
('jfuentes@madrepaulina.cl', 'Jonathan Rodrigo Fuentes Olguín', 'teacher', 'active'),
('jjimenez@madrepaulina.cl', 'Jose Manuel Jimenez Tapia', 'teacher', 'active'),
('jvera@madrepaulina.cl', 'JOSÉ JOAQUIN VERA CONCHA', 'teacher', 'active'),
('jsandoval@madrepaulina.cl', 'José Luis Sandoval', 'teacher', 'active'),
('jnavarrete@madrepaulina.cl', 'José Luis Navarrete', 'teacher', 'active'),
('jmontecinos@madrepaulina.cl', 'José Octavio Montecinos Jiménez', 'teacher', 'active'),
('jmaldonado@madrepaulina.cl', 'Joviana Estelia Maldonado Muñoz', 'teacher', 'active'),
('jconcha@madrepaulina.cl', 'Juan Carlos Concha', 'teacher', 'active'),
('jvargas@madrepaulina.cl', 'Judith Vargas Yefi', 'teacher', 'active'),
('jvidal@madrepaulina.cl', 'Judith Angélica Vidal Urrutia', 'teacher', 'active'),
('karenzambrano@madrepaulina.cl', 'Karen Zambrano Moraga', 'teacher', 'active'),
('ksaez@madrepaulina.cl', 'Karen Sáez Erices', 'teacher', 'active'),
('karen.zambrano@madrepaulina.cl', 'Karen Zambrano', 'teacher', 'suspended'),
('kzambrano@madrepaulina.cl', 'Karen Zambrano Moraga', 'teacher', 'active'),
('kpinto@madrepaulina.cl', 'Karen Pinto Jara', 'teacher', 'suspended'),
('kgarcia@madrepaulina.cl', 'KAREN ALEJANDRA GARCIA SANTILLAN', 'teacher', 'active'),
('kbarriga@madrepaulina.cl', 'Karen Alinne Barriga Roa', 'teacher', 'active'),
('ktorres@madrepaulina.cl', 'KAREN ANDREA TORRES GAJARDO', 'teacher', 'active'),
('koliveras@madrepaulina.cl', 'Karen Makarena Oliveras Barria', 'teacher', 'suspended'),
('kvergara@madrepaulina.cl', 'Karina Vergara Urbe', 'teacher', 'suspended'),
('kmartinez@madrepaulina.cl', 'Karina Martínez', 'teacher', 'suspended'),
('kvidal@madrepaulina.cl', 'Karina Vidal Campos', 'teacher', 'active'),
('kvenegas@madrepaulina.cl', 'Katherine Venegas Fuenzalida', 'teacher', 'active'),
('klobos@madrepaulina.cl', 'Katherine Edith Lobos Ferreira', 'teacher', 'suspended'),
('lletelier@madrepaulina.cl', 'Laritza Ninoska Letelier Aguayo', 'teacher', 'active'),
('laltamirano@madrepaulina.cl', 'Laura Altamirano González', 'teacher', 'active'),
('lgarrido@madrepaulina.cl', 'Leonardo Garrido', 'teacher', 'suspended'),
('lneira@madrepaulina.cl', 'Leonardo Antonio Neira Cares', 'teacher', 'active'),
('lvillagran@madrepaulina.cl', 'Leslie Makarena Villagran Giliberto', 'teacher', 'active'),
('lmunoz@madrepaulina.cl', 'Lesly Muñoz Mella', 'teacher', 'suspended'),
('lorellana@madrepaulina.cl', 'Liliam Orellana', 'teacher', 'active'),
('lmontoya@madrepaulina.cl', 'Lissette Elizabeth Montoya Flores', 'teacher', 'active'),
('ldominguez@madrepaulina.cl', 'Loreto Alejandra Domínguez Monsalve', 'teacher', 'active'),
('lcarrasco@madrepaulina.cl', 'Loretto Carrasco', 'teacher', 'active'),
('lvergara@madrepaulina.cl', 'Luis Alejandro Vergara Torres', 'teacher', 'active'),
('lsalazar@madrepaulina.cl', 'Luis Eduardo Salazar Sepúlveda', 'teacher', 'active'),
('lbetancourt@madrepaulina.cl', 'Luz Betancourt Barrera', 'teacher', 'active'),
('lrioseco@madrepaulina.cl', 'Luz Patricia Rioseco Fraile', 'teacher', 'active'),
('lhenriquez@madrepaulina.cl', 'Luz Ximena Henriquez Flores', 'teacher', 'active'),
('mmunoz@madrepaulina.cl', 'Macarena Muñoz', 'teacher', 'active'),
('mmellado@madrepaulina.cl', 'Magaly Andrea Mellado Jaque', 'teacher', 'active'),
('morellana@madrepaulina.cl', 'Maicol Orellana Yevenes', 'teacher', 'active'),
('mcamiruaga@madrepaulina.cl', 'Marcela Camiruaga León', 'teacher', 'active'),
('mpradenas@madrepaulina.cl', 'Marcela Alejandra Pradenas Opazo', 'teacher', 'active'),
('mcifuentes@madrepaulina.cl', 'Marcela del Rosario Cifuentes Alarcón', 'teacher', 'active'),
('msoto@madrepaulina.cl', 'Margarita del Carmen Soto Tirapegui', 'teacher', 'active'),
('mvizcarra@madrepaulina.cl', 'Maria Elizabeth Vizcarra Quezada', 'teacher', 'active'),
('msandoval@madrepaulina.cl', 'Mariana Irene Sandoval Ehijos', 'teacher', 'active'),
('mrecabarren@madrepaulina.cl', 'Marinka Recabarren', 'teacher', 'active'),
('mcapponi@madrepaulina.cl', 'María Angela Capponi Martínez', 'teacher', 'active'),
('mamunoz@madrepaulina.cl', 'María Angélica Muñoz Alarcón', 'teacher', 'active'),
('mvergara@madrepaulina.cl', 'María Antonieta de los Ángeles Vergara Hurtado', 'teacher', 'active'),
('mjfajardo@madrepaulina.cl', 'María José Fajardo Guzmán', 'teacher', 'active'),
('mgonzalez@madrepaulina.cl', 'Matías González', 'teacher', 'active'),
('mosorio@madrepaulina.cl', 'Miguel Osorio Otárola', 'teacher', 'active'),
('msepulveda@madrepaulina.cl', 'Miriam Sepúlveda Jara', 'teacher', 'active'),
('malarcon@madrepaulina.cl', 'Mirza Alarcón Muñoz', 'teacher', 'active'),
('mvalencia@madrepaulina.cl', 'Mónica Valencia', 'teacher', 'active'),
('mleal@madrepaulina.cl', 'Mónica Andrea Leal Garcés', 'teacher', 'suspended'),
('mcaceres@madrepaulina.cl', 'Mónica Andrea Cáceres Cerda', 'teacher', 'active'),
('nquinones@madrepaulina.cl', 'Natacha Quiñones Contreras', 'teacher', 'active'),
('nesparza@madrepaulina.cl', 'Natalia Esparza Ortiz', 'teacher', 'active'),
('naraneda@madrepaulina.cl', 'Natalia Araneda Arias', 'teacher', 'active'),
('nsepulveda@madrepaulina.cl', 'Natalie Sepúlveda Torres', 'teacher', 'active'),
('nmorales@madrepaulina.cl', 'Nelda Ivonne Morales Mora', 'teacher', 'active'),
('nburgos@madrepaulina.cl', 'Nelson Burgos Figueroa', 'teacher', 'active'),
('nfuentes@madrepaulina.cl', 'Nelson Enrique Fuentes Abarza', 'teacher', 'active'),
('nurra@madrepaulina.cl', 'Nevadita Urra', 'teacher', 'active'),
('nfuica@madrepaulina.cl', 'Nicole Fuica Aguilera', 'teacher', 'active'),
('nmolina@madrepaulina.cl', 'Nicole Molina Paredes', 'teacher', 'active'),
('olobos@madrepaulina.cl', 'Olivia Lobos Valenzuela', 'teacher', 'suspended'),
('pelgueta@madrepaulina.cl', 'Pablo Esteban Elgueta Henríquez', 'teacher', 'active'),
('pgonzalez@madrepaulina.cl', 'Pamela González Sandoval', 'teacher', 'active'),
('pparra@madrepaulina.cl', 'Pamela del Pilar Parra Sanhueza', 'teacher', 'active'),
('psanzana@madrepaulina.cl', 'Paola Andrea Sanzana Portiño', 'teacher', 'active'),
('pinostroza@madrepaulina.cl', 'Patricia Inostroza Pino', 'teacher', 'suspended'),
('pfuentealba@madrepaulina.cl', 'Patricia Fuentealba Baeza', 'teacher', 'active'),
('pcolombo@madrepaulina.cl', 'Patricia Alejandra Colombo Pulgar', 'teacher', 'active'),
('pcastillo@madrepaulina.cl', 'Patricia Alejandra Castillo Cifuentes', 'teacher', 'active'),
('pfuentes@madrepaulina.cl', 'Patricia del Carmen Fuentes Navarrete', 'teacher', 'active'),
('paraneda@madrepaulina.cl', 'Patricia Elena Araneda Olate', 'teacher', 'suspended'),
('parojas@madrepaulina.cl', 'Patricio Rojas Ledesma', 'teacher', 'active'),
('pmunoz@madrepaulina.cl', 'Paula Andrea Muñoz Fuentealba', 'teacher', 'suspended'),
('pbeltran@madrepaulina.cl', 'Paula Montserrat Beltrán Vargas', 'teacher', 'active'),
('pfernandez@madrepaulina.cl', 'Paulina Fernandez Schaffer', 'teacher', 'active'),
('ptoledo@madrepaulina.cl', 'Pedro Gabriel Toledo Silva', 'teacher', 'suspended'),
('pfranco@madrepaulina.cl', 'Pilar Cecilia Franco Torres', 'teacher', 'active'),
('rsanhueza@madrepaulina.cl', 'Ramón Andrés Sanhueza González', 'teacher', 'suspended'),
('respaldo23@madrepaulina.cl', 'Respaldo 1', 'teacher', 'active'),
('rreyes@madrepaulina.cl', 'Ricardo Mauricio Reyes Baeza', 'teacher', 'active'),
('rgutierrez@madrepaulina.cl', 'Roberto Gutierrez', 'teacher', 'active'),
('rodrigovicente@madrepaulina.cl', 'RODRIGO VICENTE MILOS PÉREZ', 'teacher', 'active'),
('ralarcon@madrepaulina.cl', 'Rosa Alarcón Muñoz', 'teacher', 'active'),
('rgilbarra@madrepaulina.cl', 'Rose Mary Gil Barra', 'teacher', 'suspended'),
('sgarrido@madrepaulina.cl', 'Sandra Maribel Garrido Cabezas', 'teacher', 'active'),
('scontreras@madrepaulina.cl', 'Scarlet Anais Contreras Ogueda', 'teacher', 'active'),
('svilla@madrepaulina.cl', 'Sebastian Andrés Villa Pinto', 'teacher', 'suspended'),
('ssanmartin@madrepaulina.cl', 'SEBASTIAN IGNACIO SAN MARTIN BUSTOS', 'teacher', 'active'),
('shermosilla@madrepaulina.cl', 'Sebastián René Hermosilla Correa', 'teacher', 'suspended'),
('secretaria@madrepaulina.cl', 'Secretaria Administrativa', 'teacher', 'active'),
('secredireccion@madrepaulina.cl', 'Secretaria Dirección Colegio Madre Paulina', 'teacher', 'active'),
('svega@madrepaulina.cl', 'Sergio Eduardo Vega Álvarez', 'teacher', 'active'),
('silvana.torres@madrepaulina.cl', 'Silvana Andrea Torres Alvarez', 'teacher', 'active'),
('scastillo@madrepaulina.cl', 'Sofia Castillo Vergara', 'teacher', 'active'),
('soliva@madrepaulina.cl', 'Sonia Andrea Oliva Tejos', 'teacher', 'active'),
('ssaavedra@madrepaulina.cl', 'Stefani Andrea Saavedra Villegas', 'teacher', 'active'),
('sperez@madrepaulina.cl', 'Stephanie Pérez Cuevas', 'teacher', 'active'),
('srueda@madrepaulina.cl', 'Susana Marcela Rueda Vera', 'teacher', 'active'),
('tvasquez@madrepaulina.cl', 'Tamara Andrea Vásquez Melo', 'teacher', 'suspended'),
('talarcon@madrepaulina.cl', 'Tamara Valentina Alarcón Jara', 'teacher', 'active'),
('tsepulveda@madrepaulina.cl', 'Tatiana Del Carmen Sepúlveda Cisternas', 'teacher', 'active'),
('tescobar@madrepaulina.cl', 'Teresa Angélica Escobar Ramos', 'teacher', 'active'),
('vconcha@madrepaulina.cl', 'Valentina Concha', 'teacher', 'active'),
('vortega@madrepaulina.cl', 'Valentina Ortega Vera', 'teacher', 'active'),
('vmartinez@madrepaulina.cl', 'Valentina Beatriz Martinez Guajardo', 'teacher', 'active'),
('vfuentes@madrepaulina.cl', 'Valeria Fuentes Pérez', 'teacher', 'active'),
('vvivanco@madrepaulina.cl', 'Valeska Karen Vivanco Morales', 'teacher', 'suspended'),
('vdias@madrepaulina.cl', 'Vanesa Días Cifuentes', 'teacher', 'active'),
('vsanhueza@madrepaulina.cl', 'Vanesa Sanhueza Rosales', 'teacher', 'suspended'),
('vgomez@madrepaulina.cl', 'Victoria Lorena Gomez Leal', 'teacher', 'active'),
('vorozco@madrepaulina.cl', 'Víctor Orozco', 'teacher', 'active'),
('wmartinez@madrepaulina.cl', 'Walter Martinez', 'teacher', 'active'),
('xcortes@madrepaulina.cl', 'Ximena Cortés Naranjo', 'teacher', 'active'),
('yduran@madrepaulina.cl', 'Yasmín Andrea Durán González', 'teacher', 'active'),
('ygallegos@madrepaulina.cl', 'Yessenia Gallegos Bizama', 'teacher', 'active'),
('yguerrero@madrepaulina.cl', 'Yezabel Guerrero Garrido', 'teacher', 'active'),
('ygutierrez@madrepaulina.cl', 'Yolanda Virginia Gutiérrez Olivares', 'teacher', 'active')
ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name, status = EXCLUDED.status;
